version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: cubos-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: cubos
      POSTGRES_PASSWORD: cubos123
      POSTGRES_DB: cubos_interview
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cubos -d cubos_interview"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: cubos-pgadmin
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@cubos.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  # Backend (exemplo para futuro)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cubos-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      # Database
      DATABASE_URL: "postgresql://cubos:cubos123@postgres:5432/cubos_interview?schema=public"

      # JWT
      JWT_SECRET: "your-super-secret-key"
      JWT_EXPIRES_IN: "7d"

      # Server
      PORT: 3000
      NODE_ENV: "development"
      FRONTEND_URL: "http://localhost:5173"

      # Cloudflare R2
      R2_PUBLIC_URL: "https://pub-9ebfed913b894a9480d9ad399ae4d639.r2.dev"
      R2_ADDRESS: "https://0b56a0b0443bced3627f43e926640543.r2.cloudflarestorage.com"
      R2_BUCKET_NAME: "cubos-movies"
      R2_ACCESS_KEY_ID: "05361bd721110f6eed645bd7519e9a3d"
      R2_SECRET_ACCESS_KEY: "b0386da21046c73a4da310eb2f68bc58f237e6ec350740b0b93057141924e1fe"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules

volumes:
  postgres_data:
  pgadmin_data:
